webcrdf-testbed/appsegmxr/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

##from test_sessions import views
from appsegmxr import views

urlpatterns = patterns('',
    url(r'^$',          views.Index,			    name='index'),
    url(r'^upload/',    views.Upload,			    name='upload'),
    url(r'^uploadfdb/', views.UploadFromDB,		    name='uploadfdb'),
    url(r'^clean/',     views.cleanUplodedData,     name='clean'),
    url(r'^getinfo/',   views.getInfoAboutImages,   name='getinfo'),
    url(r'^gallery/',   views.ImageGallery,         name='gallery'),
)

webcrdf-testbed/webcrdf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from webcrdf import views

urlpatterns = patterns('',
##    url(r'^admin/', 	include(admin.site.urls)),
    url(r'^$',		views.Index,  name='main-home'),
    url(r'^login/',	views.Login,  name='main-login'),
    url(r'^logout/',	views.Logout, name='main-logout'),
    url(r'^appwebcam/',	views.WebCamSearch, name='main-webcam'),
    # url(r'^appcbir/',	include('appcbir.urls',  namespace='appcbir', app_name='appcbir')),
    # url(r'^appxray/',	include('appxray.urls',  namespace='appxray', app_name='appxray')),
    url(r'^appsegmxr/',	include('appsegmxr.urls',  namespace='appsegmxr', app_name='appsegmxr')),
    # url(r'^appmelanoma/',	include('appmelanoma.urls',  namespace='appmelanoma',   app_name='appmelanoma')),
    # url(r'^appsegmct/',	    include('appsegmct.urls',    namespace='appsegmct',     app_name='appsegmct')),
    # url(r'^appdrugres/',	include('appdrugres.urls',   namespace='appdrugres',    app_name='appdrugres')),
    # url(r'^apphistology/',	include('apphistology.urls', namespace='apphistology',  app_name='apphistology')),
    # url(r'^appvideocbir/',	include('appvideocbir.urls', namespace='appvideocbir',  app_name='appvideocbir')),
)

webcrdf-testbed/appsegmxr/models.py
from django.db import models

# Create your models here.

webcrdf-testbed/appsegmxr/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse

from webcrdf.settings import taskManagerSegmXR

from django import forms

import random
import os
import glob
import shutil
import json
import time

# Create your views here.
################################################
def Index(request):
    print 'static URL: %s' % settings.STATIC_ROOT_XRAY_USERDATA
    print 'path: [%s]' % request.path
    if 'is_logged' in request.session:
        userName = 'Unknown'
        if 'username' in request.session:
            userName = request.session['username']
        uploadedImages=getUploadedImageList(request.session.session_key)
        context={'userName': userName, 'uploadedImages': uploadedImages}
        return render(request, 'appsegmxr.html', context)
    else:
        context={'next': '/appsegmxr/'}
        # return render(request, 'login.html', context)
        return HttpResponseRedirect('/login/?next=%s' % request.path)

################################################
def getInfoAboutImages(request):
    if not 'is_logged' in request.session:
        return HttpResponseRedirect( reverse('appsegmxr:index') )  ##('/')
    sessionId = request.session.session_key
    wdir='%s/%s' % (settings.STATIC_ROOT_SEGMXR_USERDATA, sessionId)
    # lstImg=glob.glob('%s/*' % wdir)
    lstDir=glob.glob('%s/*' % wdir)
    cnt = 0
    ret=[]
    for dd in lstDir:
        if not os.path.isdir(dd):
            continue
        ddbn=os.path.basename(dd)
        ii='%s/%s' % (dd, ddbn)
        if os.path.isfile(ii):
            tfimg=os.path.basename(ii)
            isFinished=False
            isGood=True
            tfMask='%s_mask.png' % tfimg
            tfMasked='%s_masked.png' % tfimg
            tfZip='%s.zip' % tfimg
            tfErr='%s.err' % tfimg
            tUrl    = '%s/users_segmxr/%s/%s' % (settings.STATIC_URL, sessionId, tfimg)
            tUrlZip =  '%s/users_segmxr/%s/%s' % (settings.STATIC_URL, sessionId, tfZip)
            if os.path.isfile('%s/%s' % (dd, tfMasked)):
                tUrlSegm = '%s/users_segmxr/%s/%s/%s' % (settings.STATIC_URL, sessionId, tfimg, tfMasked)
                isFinished=True
            else:
                tUrlSegm = '%s/users_segmxr/%s/%s/%s' % (settings.STATIC_URL, sessionId, tfimg, tfimg)
            if os.path.isfile('%s/%s' % (dd, tfErr)):
                isGood = False
            tIdx     = 'imguser_idx_%05d' % cnt
            timgInfo = {'url': tUrl, 'urlSegm':tUrlSegm, 'urlZip':tUrlZip, 'w': 200, 'h': 200, 'idx': tIdx, 'isFinished': isFinished, 'isGood': isGood}
            ret.append( timgInfo )
        cnt +=1
    return HttpResponse(json.dumps(ret))

################################################
def ImageGallery(request):
    num=10
    try:
        num=request.POST['num']
    except:
        pass
    if len(settings.IMAGEDB)<num:
        num=len(settings.IMAGEDB)
    ret=[]
    for ii in xrange(0,num):
        tmp=settings.IMAGEDB[ii]
        ret.append(tmp)
    return HttpResponse(json.dumps(ret))

################################################
class ImageUplInfo:
    def __init__(self, url, size, idx):
        self.url=url
        self.sizeW=size[0]
        self.sizeH=size[1]
        self.idx=idx

def getUploadedImageList(sessionId):
    wdir='%s/%s' % (settings.STATIC_ROOT_SEGMXR_USERDATA, sessionId)
    lstDir=glob.glob('%s/*' % wdir)
    # lstImg=glob.glob('%s/*' % wdir)
    ret=[]
    cnt = 0
    for dd in lstDir:
        if not os.path.isdir(dd):
            continue
        ddbn=os.path.basename(dd)
        ii='%s/%s' % (dd, ddbn)
        if os.path.isfile(ii):
            tfimg=os.path.basename(ii)
            # tIdx     = 'imguser_%s' % tfimg
            tIdx     = 'imguser_idx_%05d' % cnt
            timgInfo = ImageUplInfo('%s/users_segmxr/%s/%s/%s' % (settings.STATIC_URL, sessionId, tfimg, tfimg), (200,200), tIdx)
            ret.append( timgInfo )
        cnt+=1
    return ret

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()

def Upload(request):
    if not 'is_logged' in request.session:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # odir='%s/%s' % (settings.STATIC_ROOT_SEGMXR_USERDATA, request.session.session_key)
            fout=request.FILES['file']
            odir='%s/%s/%s' % (settings.STATIC_ROOT_SEGMXR_USERDATA, request.session.session_key, fout)
            handle_uploaded_file(odir, fout)
        return HttpResponseRedirect( reverse('appsegmxr:index') )  ##('/')
    else:
        form = UploadFileForm()
    return render_to_response('appsegmxr.html', {'form': form})

def UploadFromDB(request):
    if not 'is_logged' in request.session:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        try:
            fname=request.POST['fname']
            fnFrom="%s/%s" % (settings.STATIC_ROOT_XRAY_DBDATA,   fname)
            toDir ="%s/%s/%s" % (settings.STATIC_ROOT_SEGMXR_USERDATA, request.session.session_key,fname)
            if not os.path.isdir(toDir):
                try:
                    os.makedirs(toDir)
                except:
                    print "ERROR: Can't create directory [%s]" % toDir
            fnTo  ="%s/%s" % (toDir, fname)
            print ":: [%s] ---> [%s]" % (fnFrom, fnTo)
            if not os.path.isfile(fnTo):
                if os.path.isfile(fnFrom):
                    shutil.copyfile(fnFrom, fnTo)
                    taskManagerSegmXR.appendTaskSegmXR(fnTo)
        except:
            print "ERROR: Can't copy file from [%s] to [%s]" % (fnFrom, fnTo)
        return HttpResponse(json.dumps([]))
    else:
        return HttpResponseRedirect( reverse('appxray:index') )

def handle_uploaded_file(odir, f):
    if not os.path.isdir(odir):
        os.makedirs(odir)
    fout='%s/%s' % (odir, f.name)
    print fout
    with open(fout, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    taskManagerSegmXR.appendTaskSegmXR(fout)

def cleanUplodedData(request):
    if not 'is_logged' in request.session:
        return HttpResponseRedirect( reverse('appsegmxr:index') )  ##('/')
    wdir='%s/%s' % (settings.STATIC_ROOT_SEGMXR_USERDATA, request.session.session_key)
    if not os.path.isdir(wdir):
        return HttpResponseRedirect( reverse('appsegmxr:index') ) ##('/')
    shutil.rmtree(wdir)
    return HttpResponseRedirect( reverse('appsegmxr:index') ) ##('/')

webcrdf-testbed/templates/appsegmxr.html
{% extends "base.html" %}
{% block content %}
    <link href="/data/cssjs/ekko-lightbox.min.css" type="text/css">
    <script src="/data/cssjs/ekko-lightbox.min.js" type="text/javascript"></script>
    <style type="text/css">
        .container00 {
            position: relative;
            width: 200px;
            height: 200px;
            display: inline-block;
        }
        .main_image00 {
            width: 100%;
            height: 100%;
        }
        .overlay_image00 {
            position: absolute;
            top: 10px;
            left: 10px;
        }
    </style>
<div class="container-fluid fill-heigth">
<div class="row fill-heigth">
    <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3 content">
        <h4> <kbd>1</kbd> Upload your X-Ray chest images:</h4><hr/>
        {% block upload %}
            <form role="form" id="id_form_upload" style="padding: 2px" enctype="multipart/form-data" method="post" action="{% url 'appsegmxr:upload' %}">
                <div class="btn-group-vertical">
                    <input class="btn btn-primary" type="file" value="file" name="file" id="id_file" />
                    <a class="btn btn-danger" href="{% url 'appsegmxr:clean' %}"><span class="glyphicon glyphicon-remove-circle"></span> Remove files</a>
{#                    <a href="#" class="btn btn-success btn-block" id="id_showdb" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-th"></span> Show Database</a>#}
                    <a href="#" class="btn btn-success btn-block" id="id_showdb" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-th"></span> Select from a Database</a>
                </div>
            </form>
        {% endblock %}
    </div>
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7 content" style="text-align: center" id="canvas_container"  style="display: table-row;">
        <h4> <kbd>2</kbd> Segmentation results:</h4><hr/>
        <div id="user_images" style="min-height: 300px;">
        {% for ii in uploadedImages %}
            <a id="a_{{ ii.idx }}" class="container00" href="{{ ii.url }}" data-toggle="lightbox" data-title="{{ ii.idx }}" data-footer="{{ ii.sizeW }}x{{ ii.sizeH }}" data-buttona="Download">
                <img class="img-thumbnail img-user" alt="100x100" src="{{ ii.url }}" style="width: {{ ii.sizeW }}px; height: {{ ii.sizeH }}px;" id="{{ ii.idx }}">
                <i class="overlay_image00 fa fa-refresh fa-inverse fa-spin fa-3x" id="info_{{ ii.idx }}"></i>
            </a>
        {% endfor %}
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width: 90%; height: 90%">
    <div class="modal-content" style="width: 100%; height: 100%">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">X-Ray database</h4>
      </div>
      <div class="modal-body" style="width: 100%; height: 80%; overflow: scroll;" id="idx_gallery"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="gallery-close">Close</button>
      </div>
    </div>
  </div>
</div>


</div>

<script type="application/javascript">
    var currentImageInfo = null;
    $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox.defaults.onShow = function() {
            console.log("::onShow()");
            $("#lightbox_btna").on("click", function() {
                var urlZip = $("#lightbox_img_href").attr('src');
                //TODO: This IS STUPID HAK(FUCK)!!!!
                urlZip = urlZip.substr(0,urlZip.length-11) + ".zip";
{#                $.fileDownload(urlZip);#}
                window.location=urlZip;
                console.log("::onClick() : " + urlZip);
            });
        };
        return $(this).ekkoLightbox();
    });
    $(function () {
        var timeCounter = 0;
        var timeDelay   = 1000;
        ///////////////////////////////////////
        function imageListUpdater() {
            $.ajax({
                url: "{% url 'appsegmxr:getinfo' %}",
                success: function(data) {
                    currentImageInfo = $.parseJSON(data);
                    console.log(currentImageInfo);
                    var isAllFinished = true;
                    var tStatus, tIdx;
                    for(var ii=0; ii<currentImageInfo.length; ii++) {
                        tStatus = currentImageInfo[ii].isFinished;
                        tIdx    = currentImageInfo[ii].idx;
                        if(tStatus) {
                            $('#'   + tIdx).attr('src', currentImageInfo[ii].urlSegm);
                            $('#a_' + tIdx).attr('href',currentImageInfo[ii].urlSegm);
                            $('#info_' + tIdx).hide();
                        } else {
{#                            $('#'   + tIdx).attr('src', currentImageInfo[ii].url);#}
{#                            $('#a_' + tIdx).attr('href',currentImageInfo[ii].url);#}
                            $('#info_' + tIdx).show();
                            isAllFinished = false;
                        }
                    }
                    if(!isAllFinished) {
                        updateImageList();
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log("ERROR[Ajax] : status=" + textStatus);
                }
            });
        }
        function updateImageList() {
            var currDelay = 100;
            if(timeCounter>0) {
                currDelay=timeDelay;
            }
            setTimeout(function() {
                console.log("Timeout: " + timeCounter);
                timeCounter++;
                imageListUpdater();
            }, currDelay);
        }
        updateImageList();
        ///////////////////////////////////////
        $("#id_help").tooltip({html:true});
        $("#navbar-segmxr").addClass("active");
        $('.alert .close').on('click', function(e) {
            $(this).parent().hide();
        });

        $("#id_file").on("change", function() {
            $("#id_form_upload").submit();
        });
        var funShowErrorMessage = function(txt) {
            $('#message-error-text').html(txt);
            $('#message-error').show();
        };
    /////////////////////////////////////////////////
        $("#id_showdb").on('click', function () {
            var gal = $('#idx_gallery');
            var param={'num': 10};
            $.ajax({
                url: "{% url 'appsegmxr:gallery' %}",
                type: "POST",
                data: param,
                success: function (data, textStatus, jqXHR) {
                    var tobj = $.parseJSON(data);
                    var dataLen=tobj.length;
                    var maxSiz=200;
                    gal.empty();
                    for(var ii=0; ii<dataLen; ii++) {
                        var tUrl = tobj[ii].url;
                        var pw = 1;
                        var ph = 1;
                        if (tobj[ii].w >= tobj[ii].h) {
                            pw = maxSiz;
                            ph = Math.floor(maxSiz * tobj[ii].h / tobj[ii].w);
                        } else {
                            pw = Math.floor(maxSiz * tobj[ii].w / tobj[ii].h);
                            ph = maxSiz;
                        }
                        var tmpImg = $('<img>',{
                            class: 'img-thumbnail',
                            width:  pw,
                            height: ph,
                            id:  'gal_'+tobj[ii].idx,
                            src: tUrl
                        });
                        $(tmpImg).on('click', function() {
                            var spl = this.src.split('/');
                            var fn  = spl[spl.length-1];
                            console.log(fn);
                            $('#gallery-close').click();
                            var param2={'fname': fn};
                            $.ajax({
                                url: "{% url 'appsegmxr:uploadfdb' %}",
                                type: "POST",
                                data: param2,
                                success: function (data, textStatus, jqXHR) {
                                    console.log(data);
                                    window.location="{% url 'appsegmxr:index' %}";
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    funShowErrorMessage('Server error: bad image in DB');
                                }
                            });
                            //window.location="/";
                        });
                        $(tmpImg).css('cursor','pointer');
                        $(tmpImg).prop('title', 'Press mouse button to add image');
                        gal.append(tmpImg);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    funShowErrorMessage('Error gallery query...');
                }
            });
        });
    /////////////////////////////////////////////////
        /*
        $("#user_images img").on('click', function () {
            console.log('fuck:' + $(this).attr('id'));
            funLoadImageToCanvas(this);
        });
        var funLoadImageToCanvas = function (imgLink) {
            imageIsLoaded = false;
            imageCurrent = new Image();
            imageCurrent.src = imgLink.src;
            imageCurrent.onload = function () {
                ctxMaxSize = $("#canvas_container").width()-80;
                var tmpMax = Math.max(this.width, this.height);
                imageCurrentW = this.width;
                imageCurrentH = this.height;
                if (this.width>this.height) {
                    canvasW  = ctxMaxSize;
                    canvasH = Math.floor(ctxMaxSize*this.height/this.width);
                } else {
                    canvasH = ctxMaxSize;
                    canvasW  = Math.floor(ctxMaxSize*this.width/this.height);
                }
                imageCurrentK = imageCurrentW/canvasW;
                Rect.x1 = Math.floor(0.01*canvasW);
                Rect.x2 = Math.floor(0.20*canvasW);
                Rect.y1 = Math.floor(0.01*canvasH);
                Rect.y2 = Math.floor(0.20*canvasH);
                canvas.width  = canvasW;
                canvas.height = canvasH;
                ctx = canvas.getContext('2d');
                imageCurrIdx = $(imgLink).attr('id');
                updateCanvasRect();
            };
        };
        */
    /////////////////////////////////////////////////
    });
</script>

{% endblock %}

webcrdf-testbed/templates/appwebcam.html
{% extends "base.html" %}
{% block content %}
    <link rel="stylesheet" href="/data/cssjs/webcam_style.css">
    <video id="webcam" width="480" height="360" style="display:none;"></video>
<div class="fill-height">
    <div class="col-sm-7 content" style="text-align: center">
                <div class="row-fluid">
                    <div class="span8 center-div">
                        <h4> <kbd>1</kbd> Current WebCam image:</h4>
                        <canvas id="canvas" width="480px" height="360px"></canvas>
                        <br/>
                        <div class="row">
                            <button id="btn-capture" type="button" class="btn btn-large btn-success active" data-toggle="button">Start/Stop Capture</button>
                            <button id="btn-search"  type="button" class="btn btn-large btn-success active" data-toggle="button">Start/Stop Search</button>
                            <a class="btn btn-large btn-danger" id="btn-clear">Clear Frames</a>
                        </div>
                        <hr/>
                        <h4> <kbd>2</kbd> Current WebCam search-query results:</h4>
                        <hr>
                        <div class="span12" id="frame-search"></div>
                    </div>
                </div>
    </div>
    <div class="col-sm-4 content fill-height" style="text-align: center" id="canvas_container" style="display: table">
        <h4> <kbd>3</kbd> Image database:</h4>
        <h2 class="frm-label" id="frm-label">...</h2>
        <div class="span8 img_list fill-height" id="frame-list"></div>
    </div>
</div>

            <!--div class="container-fluid fill-heigth">

            </div-->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script type="text/javascript" src="/data/cssjs/webcam_compatibility.js"></script>
        <script type="text/javascript" src="/data/cssjs/webcam_profiler.js"></script>
        <script type="text/javascript">
        $(window).load(function() {
            $("#navbar-webcam").addClass("active");
            "use strict";
            var canvas  = document.getElementById('canvas');
            var video   = document.getElementById('webcam');
            var cntStep         = 0;
            var STEP            = 3;
            var cntFrame        = 0;
            var maxListFrames   = 100;
            var arrayDsc        = new Array();
            var arrayImg        = new Array();
            var numFrmSearch    = 5;
            $("#btn-capture, #btn-search").click(function () {
                if($(this).hasClass('active')) {
                    $(this).removeClass('btn-success');
{#                    $(this).removeClass('active');#}
                } else {
                    $(this).addClass('btn-success');
{#                    $(this).addClass('active');#}
                }
            });
            $("#btn-clear").click(function () {
                $("#frame-list").empty();
                arrayImg.splice(0, arrayImg.length);
                arrayDsc.splice(0, arrayDsc.length);
            });
            var calcDistL1 = function (vDsc1, vDsc2 ) {
                return vDsc1.reduce(function (v1, v2, idx) { return v1+=Math.abs(v2-vDsc2[idx]) });
            };
            var calcBestIdx = function (vDsc) {
                var numDsc  = arrayDsc.length;
                var dst = arrayDsc.map(function (x) { return calcDistL1(vDsc,x)});
                var idx = Array.apply(null, Array(dst.length)).map(function (_, i) {return i;});
                idx.sort(function (i1,i2) { return (dst[i1]-dst[i2])});
                return idx;
            };

            try {
                compatibility.getUserMedia({video: true}, function(stream) {
                    try {
                        video.src = compatibility.URL.createObjectURL(stream);
                    } catch (error) {
                        video.src = stream;
                    }
                    setTimeout(function() {
                            video.play();
                            demo_app();
                            compatibility.requestAnimationFrame(tick);
                        }, 500);
                }, function (error) {
                    $('#canvas').hide();
                    $('#log').hide();
                    $('#no_rtc').html('<h4>WebRTC not available.</h4>');
                    $('#no_rtc').show();
                });
            } catch (error) {
                $('#canvas').hide();
                $('#log').hide();
                $('#no_rtc').html('<h4>Something goes wrong...</h4>');
                $('#no_rtc').show();
            }
            var stat = new profiler();
            var ctx,canvasWidth,canvasHeight;
            var frameListWidth,frameListHeight;

            function demo_app() {
                canvasWidth     = canvas.width;
                canvasHeight    = canvas.height;
                var minFrameListSize    = 180;
                if(canvasWidth>canvasHeight) {
                    frameListWidth  = minFrameListSize;
                    frameListHeight = Math.round((minFrameListSize*canvasHeight)/canvasWidth);
                } else {
                    frameListWidth  = Math.round((minFrameListSize*canvasWidth)/canvasHeight);
                    frameListHeight = minFrameListSize;
                }
                for(var ii=0; ii<numFrmSearch; ii++) {
                    $("#frame-search").append($('<img>',{
                        class: 'frm-search',
                        width: frameListWidth,
                        height: frameListHeight
                    }));
                }
                ctx  = canvas.getContext('2d');
                ctx.fillStyle = "rgb(255,0,0)";
                ctx.font      = "60px Arial";
                ctx.strokeStyle = "rgb(0,255,0)";
                stat.add("calc descriptor");
            }
            function tick() {
                compatibility.requestAnimationFrame(tick);
                stat.new_frame();
                if (video.readyState === video.HAVE_ENOUGH_DATA) {
                    cntStep++;
                    if(cntStep<STEP) {
                        return;
                    } else {
                        cntStep=0;
                    }
                    ctx.drawImage(video, 0, 0, canvasWidth, canvasHeight);
                    var imageData = ctx.getImageData(0, 0, canvasWidth, canvasHeight);
                    ctx.fillText(""+cntFrame, 70, 70);
                    cntFrame++;
                    var str = ""+cntFrame+"/"+(arrayDsc.length+1)+"/"+maxListFrames;
                    $("#frm-label").html(str);
                    var tmpData = canvas.toDataURL('image/png');
                    var data_u32 = new Uint32Array(imageData.data.buffer);
                    var r_shift=(0xff<<0);
                    var g_shift=(0xff<<8);
                    var b_shift=(0xff<<16);
                    var nBin=2;
                    var dataIdx = Array.prototype.map.call(data_u32, function (num) {
                        return  (((num&r_shift)>>(0 +8-nBin))<<(0*nBin))|
                                (((num&g_shift)>>(8 +8-nBin))<<(1*nBin))|
                                (((num&b_shift)>>(16+8-nBin))<<(2*nBin));
                    });
                    var dscHist=Array.apply(null, new Array(1<<(3*nBin))).map(Number.prototype.valueOf,0);
                    dataIdx.forEach(function(element, index, array){dscHist[element]+=1;});
                    if($("#btn-search").hasClass('active')) {
                        if($("#frame-list img").length>numFrmSearch) {
                            var srtIdx = calcBestIdx(dscHist);
                            var lstFrmSearch = $("#frame-search img");
                            for(var ii=0; ii<numFrmSearch; ii++) {
                                $(lstFrmSearch[ii]).attr('src',arrayImg[srtIdx[ii]]);
                            }
                        }
                    }
                    if($("#btn-capture").hasClass('active')) {
                        console.log("btn-capture: active");
                        $("#frame-list").prepend($('<img>', {
                            src: tmpData,
                            with:   100,
                            height: 100
                        }));
                        arrayDsc.push(dscHist);
                        arrayImg.push(tmpData);
                        if($("#frame-list img").length>maxListFrames) {
                            $("#frame-list img").last().remove();
                            arrayDsc.shift();
                            arrayImg.shift();
                        }
                    } else {
                        console.log("btn-capture: non-active");
                    }
//                    console.log(dscHist);
                    $('#log').html(stat.log());
                }
            }
            $(window).unload(function() {
                video.pause();
                video.src=null;
            });
        });
        </script>
{% endblock %}

webcrdf-testbed/templates/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <title>Login Form</title>
</head>
<body role="document" style="padding: 8px;">
    <div class="container theme-showcase">
        <div class="jumbotron">
            <h1>Hello, User!</h1>
            <p>Please login for to continue working on our portal...</p>
            {% if next %}
        	<p><a href="/login/?next={{ next }}" class="btn btn-primary btn-lg" role="button">Continue</a></p>
            {% else %}
        	<p><a href="/login/" class="btn btn-primary btn-lg" role="button">Login</a></p>
            {% endif %}
        </div>
    </div>
</body>
</html>